services:
  callq-department2:
    build:
      context: .
    container_name: callq-department2
    network_mode: host
    env_file:
      - .env.department2
    volumes:
      - ./logs:/app/logs
      - ./acc_google_api:/app/acc_google_api:ro
      - ./prompts:/app/prompts:ro
    restart: "no"
