services:
  callq-department1:
    build: .
    container_name: callq-department1
    dns:
      - 8.8.8.8
      - 1.1.1.1
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./acc_google_api:/app/acc_google_api:ro
      - ./prompts:/app/prompts:ro
    restart: "no"
